#!/bin/bash
export TOOLWD="$(pwd)"
export WD="${TOOLWD}"
export PBP="${WD}/pbp"
export PATH="${PBP}:$PATH"
export PYTHONPATH="${PBP}/kernel:${PYTHONPATH}"
# T2TLIBD is the lib directory for t2t - PBP tools should not contain hard-coded directory paths
export T2TLIBD="${PBP}/t2td/lib"
