#!/bin/bash

######### commands specific to this project #############
# TOP LEVEL
# env:
#  $PATH
#  $TOOLWD ($(pwd))
#  $CALLERPATH
#  $TARGET
#  $PYTHONPATH

transmog=smdpl
source ./@defc

# 1. rebuild the transmogrifier ("compiler") every time...
das2json ${transmog}.drawio
python ${transmog}.py "${TARGET}".drawio main ${transmog}.drawio.json | splitoutputs
checkfailure
cat out.py | python replace.py "✣" "${TARGET}" >"${CALLERPATH}/${TARGET}.py"
./@testc

echo ' *** DONE ***'

############################



