#!/bin/bash

######### commands specific to this project #############
# env vars that may be used in this script:
#  $PATH
#  $TOOLWD ($(pwd))
#  $CALLERPATH
#  $TARGET
#  $PYTHONPATH

transmog=smdpl

# 1. rebuild the transmogrifier ("compiler") every time...
das2json ${transmog}.drawio
python ${transmog}.py "${CALLERPATH}/${TARGET}".drawio main ${transmog}.drawio.json | splitoutputs
checkfailure
mv out.py "${CALLERPATH}/${TARGET}.py"

############################



