#!/bin/bash
echo ' *** TEST ***'
# 3. run the test jig, which includes looper.py. The test jig, itself, is drawn as a diagram "testjig.drawio" and needs "testermain.py" to kick it off
# and installs the parts (formatted for use in the diagram) needed by the test jig ("stimulus.py" and "testenvelope.py" (which imports "looper.py"))

echo
echo '*** automated test ***'
#export PBPSTEPPING="1"
das2json testjig.drawio
python testermain.py "" test testjig.drawio.json

echo
echo '*** looper.py ***'
cat looper.py

echo
echo
echo '*** the above is the output from testjig.drawio followed by the generated Python code ***'
echo '*** (use the drawio editor (drawio.com) to view testjig.drawio if you wish) ***'
