#!/bin/bash
${PBP}/pbplog "in pbp/t2t T2TVERBOSE=${T2TVERBOSE}"
set -e

if [ "$#" -eq 1 ]; then
  grammar="${WD}/$1.ohm"
  rewrite="${WD}/$1.rwr"
elif [ "$#" -eq 2 ]; then
  grammar="${WD}/$1.ohm"
  rewrite="${WD}/$2.rwr"
else
  echo "Usage: $0 base            # uses base.ohm and base.rwr" >&2
  echo "   or: $0 grammar-base rewrite-base" >&2
  exit 1
fi
src=-

# wsupport is support.js in the current working directory
wsupport="${WD}/support.mjs"


node "${T2TLIBD}/rwr.mjs" "${rewrite}" >"${WD}/temp.rewrite.mjs"

sed -e 's/`/` + "`" + String.raw`/g' <"${grammar}" >"${WD}/temp.grammar"

nanodsl="${WD}/temp.nanodsl.${RANDOM}.mjs"

cat "${T2TLIBD}/front.part.js" "${WD}/temp.grammar" "${T2TLIBD}/middle.part.js" "${T2TLIBD}/args.part.js" "${wsupport}" "${WD}/temp.rewrite.mjs" "${T2TLIBD}/tail.part.js" >"${nanodsl}"

node "${nanodsl}" "${src}"
